sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before _install:
  ## gcloud configuration
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project deep-way-401314
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials cluster-k8s
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hungvi/client-test -f ./client/Dockerfile.dev ./client
  - docker build -t hungvi/server-test -f ./server/Dockerfile.dev ./server

script:
  - docker run -e CI=true hungvi/client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main