apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vonga-online-com-tls
spec:
  sercretName: vonga-online-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vonga.online
  dnsNames:
    - vonga.online
    - www.vonga.online
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - vonga.online
          - www.vonga.online

