apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: vonga-online-tls
spec:
  secretName: vonga-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vonga.online
  dnsNames:
    - vonga.online
    - www.vonga.online