apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: rallycoding/multi-client-k8s
        resources:
          limits:
            memory: "384Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000